// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnswerQuestion(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnswerQuestion'](arg1, arg2, arg3);
}

export function CancelRun(arg1, arg2) {
  return window['go']['main']['App']['CancelRun'](arg1, arg2);
}

export function CheckConnection(arg1) {
  return window['go']['main']['App']['CheckConnection'](arg1);
}

export function ClearConnectionKey(arg1) {
  return window['go']['main']['App']['ClearConnectionKey'](arg1);
}

export function ConfirmVersion(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConfirmVersion'](arg1, arg2, arg3);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateWorkflow(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWorkflow'](arg1, arg2, arg3);
}

export function Dashboard(arg1) {
  return window['go']['main']['App']['Dashboard'](arg1);
}

export function DecideApproval(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DecideApproval'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DecideToolApproval(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecideToolApproval'](arg1, arg2, arg3);
}

export function DeleteRole(arg1) {
  return window['go']['main']['App']['DeleteRole'](arg1);
}

export function DetectPaths() {
  return window['go']['main']['App']['DetectPaths']();
}

export function EnsureTestConnection() {
  return window['go']['main']['App']['EnsureTestConnection']();
}

export function EventsAfter(arg1, arg2) {
  return window['go']['main']['App']['EventsAfter'](arg1, arg2);
}

export function GetOrganization() {
  return window['go']['main']['App']['GetOrganization']();
}

export function GetRun(arg1, arg2) {
  return window['go']['main']['App']['GetRun'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWorkflow(arg1, arg2) {
  return window['go']['main']['App']['GetWorkflow'](arg1, arg2);
}

export function Inbox() {
  return window['go']['main']['App']['Inbox']();
}

export function InstructionPreview(arg1, arg2) {
  return window['go']['main']['App']['InstructionPreview'](arg1, arg2);
}

export function ListAssignments(arg1) {
  return window['go']['main']['App']['ListAssignments'](arg1);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListRoles() {
  return window['go']['main']['App']['ListRoles']();
}

export function ListRuns(arg1) {
  return window['go']['main']['App']['ListRuns'](arg1);
}

export function ListWorkflows(arg1) {
  return window['go']['main']['App']['ListWorkflows'](arg1);
}

export function PauseRun(arg1, arg2) {
  return window['go']['main']['App']['PauseRun'](arg1, arg2);
}

export function Ping(arg1) {
  return window['go']['main']['App']['Ping'](arg1);
}

export function ReadArtifact(arg1, arg2) {
  return window['go']['main']['App']['ReadArtifact'](arg1, arg2);
}

export function ResumeRun(arg1, arg2) {
  return window['go']['main']['App']['ResumeRun'](arg1, arg2);
}

export function RetryStep(arg1, arg2, arg3) {
  return window['go']['main']['App']['RetryStep'](arg1, arg2, arg3);
}

export function SaveAssignment(arg1) {
  return window['go']['main']['App']['SaveAssignment'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveRole(arg1) {
  return window['go']['main']['App']['SaveRole'](arg1);
}

export function SaveWorkflowDraft(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveWorkflowDraft'](arg1, arg2, arg3, arg4);
}

export function SetConnectionKey(arg1, arg2) {
  return window['go']['main']['App']['SetConnectionKey'](arg1, arg2);
}

export function SetProjectArchived(arg1, arg2) {
  return window['go']['main']['App']['SetProjectArchived'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function StartRun(arg1, arg2) {
  return window['go']['main']['App']['StartRun'](arg1, arg2);
}

export function SubmitHumanResult(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SubmitHumanResult'](arg1, arg2, arg3, arg4);
}

export function SubmitReview(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SubmitReview'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SystemStatus() {
  return window['go']['main']['App']['SystemStatus']();
}

export function TestConnectionCall(arg1, arg2) {
  return window['go']['main']['App']['TestConnectionCall'](arg1, arg2);
}

export function UpdateOrganization(arg1, arg2) {
  return window['go']['main']['App']['UpdateOrganization'](arg1, arg2);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function ValidateWorkflow(arg1, arg2) {
  return window['go']['main']['App']['ValidateWorkflow'](arg1, arg2);
}

export function WorkflowTemplates() {
  return window['go']['main']['App']['WorkflowTemplates']();
}
