// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Ping(arg1) {
  return window['go']['main']['App']['Ping'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SystemStatus() {
  return window['go']['main']['App']['SystemStatus']();
}
