// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {connect} from '../models';
import {domain} from '../models';
import {engine} from '../models';
import {storage} from '../models';
import {templates} from '../models';

export function AnswerQuestion(arg1:string,arg2:string,arg3:string):Promise<main.ActionResult>;

export function CancelRun(arg1:string,arg2:string):Promise<void>;

export function CheckConnection(arg1:string):Promise<connect.Report>;

export function ClearConnectionKey(arg1:string):Promise<main.ConnectionView>;

export function ConfirmVersion(arg1:string,arg2:string,arg3:number):Promise<main.ConfirmResult>;

export function CreateProject(arg1:main.ProjectInput):Promise<domain.Project>;

export function CreateWorkflow(arg1:string,arg2:string,arg3:string):Promise<domain.Workflow>;

export function Dashboard(arg1:boolean):Promise<Array<engine.ProjectSummary>>;

export function DecideApproval(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:Array<string>):Promise<main.ActionResult>;

export function DecideToolApproval(arg1:string,arg2:string,arg3:boolean):Promise<main.ActionResult>;

export function DeleteRole(arg1:string):Promise<void>;

export function DetectPaths():Promise<main.DetectedPaths>;

export function EnsureTestConnection():Promise<domain.ProviderConnection>;

export function EventsAfter(arg1:string,arg2:number):Promise<Array<storage.EventRecord>>;

export function GetOrganization():Promise<domain.Organization>;

export function GetRun(arg1:string,arg2:string):Promise<engine.RunDetail>;

export function GetSettings():Promise<Record<string, string>>;

export function GetWorkflow(arg1:string,arg2:string):Promise<domain.Workflow>;

export function Inbox():Promise<Array<engine.InboxItem>>;

export function InstructionPreview(arg1:string,arg2:string):Promise<main.InstructionPreview>;

export function ListAssignments(arg1:string):Promise<Array<domain.Assignment>>;

export function ListConnections():Promise<Array<main.ConnectionView>>;

export function ListRoles():Promise<Array<domain.Role>>;

export function ListRuns(arg1:string):Promise<Array<engine.RunDetail>>;

export function ListWorkflows(arg1:string):Promise<Array<domain.Workflow>>;

export function PauseRun(arg1:string,arg2:string):Promise<void>;

export function Ping(arg1:string):Promise<main.PingResult>;

export function ReadArtifact(arg1:string,arg2:string):Promise<engine.ArtifactContent>;

export function ResumeRun(arg1:string,arg2:string):Promise<void>;

export function RetryStep(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveAssignment(arg1:domain.Assignment):Promise<domain.Assignment>;

export function SaveConnection(arg1:main.ConnectionInput):Promise<main.ConnectionView>;

export function SaveRole(arg1:domain.Role):Promise<domain.Role>;

export function SaveWorkflowDraft(arg1:string,arg2:string,arg3:number,arg4:string):Promise<domain.Workflow>;

export function SetConnectionKey(arg1:string,arg2:string):Promise<main.ConnectionView>;

export function SetProjectArchived(arg1:string,arg2:boolean):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function StartRun(arg1:string,arg2:string):Promise<main.StartResult>;

export function SubmitHumanResult(arg1:string,arg2:string,arg3:number,arg4:Record<string, string>):Promise<main.ActionResult>;

export function SubmitReview(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:Array<string>,arg7:Record<string, string>):Promise<main.ActionResult>;

export function SystemStatus():Promise<main.SystemStatus>;

export function TestConnectionCall(arg1:string,arg2:string):Promise<connect.Report>;

export function UpdateOrganization(arg1:string,arg2:string):Promise<void>;

export function UpdateProject(arg1:main.ProjectInput):Promise<domain.Project>;

export function ValidateWorkflow(arg1:string,arg2:string):Promise<storage.ValidationResult>;

export function WorkflowTemplates():Promise<Array<templates.Template>>;
