// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSettings():Promise<Record<string, string>>;

export function Ping(arg1:string):Promise<main.PingResult>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SystemStatus():Promise<main.SystemStatus>;
